//! # zkml-verifier
//!
//! Soroban smart contract that verifies Groth16 proofs of ML inference.
//!
//! This contract provides on-chain verification of zero-knowledge proofs
//! generated by the off-chain prover. It leverages the BN254 elliptic curve
//! host functions introduced in Stellar Protocol 25 (X-Ray) via CAP-0074,
//! and uses Poseidon hash commitments from CAP-0075.
//!
//! # Contract Interface
//!
//! - `initialize`: Register the model commitment.
//! - `verify_inference`: Accept a Groth16 proof and public inputs, verify
//!   correctness, record the result, and emit an event.
//! - `get_result`: Query the last verified inference result.
//! - `get_model_hash`: Query the registered model commitment.
//! - `get_verification_count`: Query how many proofs have been verified.

#![no_std]

use soroban_sdk::crypto::bn254::{Bn254Fr, Bn254G1Affine, Bn254G2Affine};
use soroban_sdk::{
    contract, contracterror, contractimpl, contracttype, log, symbol_short, vec, Bytes, Env,
    Symbol, Vec, U256,
};

// Storage keys
const MODEL_HASH: Symbol = symbol_short!("mdl_hash");
const VERIFICATION_KEY: Symbol = symbol_short!("vk");
const LAST_RESULT: Symbol = symbol_short!("lst_res");
const INITIALIZED: Symbol = symbol_short!("init");
const VERIFY_CNT: Symbol = symbol_short!("vrf_cnt");
const VERIFICATION_KEY: Symbol = symbol_short!("vk_key");

/// Contract interface version, bumped on breaking interface changes.
pub const VERSION: u32 = 2;

/// Minimum protocol version required for BN254 host functions (CAP-0074).
pub const MIN_PROTOCOL_VERSION: u32 = 25;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum VerificationError {
    ContractNotInitialized = 1,
    PublicInputsTooShort = 2,
    MalformedProofA = 3,
    MalformedProofB = 4,
    MalformedProofC = 5,
    MalformedVerificationKey = 6,
    VerificationFailed = 7,
}

/// Rejection / Verification Errors
#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
pub enum VerifierError {
    NotInitialized = 1,
    AlreadyInitialized = 2,
    InvalidModelHash = 3,
    InvalidInputsLength = 4,
    InvalidProofLength = 5,
}

/// On-chain representation of BN254 Groth16 verification key.
#[contracttype]
#[derive(Clone, Debug)]
pub struct VerificationKey {
    /// G1 point alpha (64 bytes)
    pub alpha: Bytes,
    /// G2 point beta (128 bytes)
    pub beta: Bytes,
    /// G2 point gamma (128 bytes)
    pub gamma: Bytes,
    /// G2 point delta (128 bytes)
    pub delta: Bytes,
    /// IC points array (each G1 point, 64 bytes)
    pub ic: Vec<Bytes>,
}

/// On-chain record of a verified inference result.
#[contracttype]
#[derive(Clone, Debug)]
pub struct InferenceRecord {
    /// Poseidon commitment to the model that produced this result.
    pub model_hash: Bytes,
    /// The inference output value.
    pub output: Bytes,
    /// Ledger sequence number at verification time.
    pub verified_at: u32,
}

/// Groth16 verification key stored on-chain.
#[derive(Clone)]
#[contracttype]
pub struct VerificationKey {
    /// G1 point
    pub alpha: Bn254G1Affine,
    /// G2 point
    pub beta: Bn254G2Affine,
    /// G2 point
    pub gamma: Bn254G2Affine,
    /// G2 point
    pub delta: Bn254G2Affine,
    /// IC array for public input linear combination
    pub ic: Vec<Bn254G1Affine>,
}

#[contract]
pub struct ZkmlVerifierContract;

#[contractimpl]
impl ZkmlVerifierContract {
    /// Initialize the contract with a model commitment and Groth16 verification key. Call exactly once.
    /// Initialize the contract with a model commitment and verification key. Call exactly once.
    pub fn initialize(env: Env, model_hash: Bytes, vk: VerificationKey) {
        if env.storage().instance().has(&INITIALIZED) {
            panic!("contract is already initialized");
        }
        env.storage().instance().set(&MODEL_HASH, &model_hash);
        env.storage().instance().set(&VERIFICATION_KEY, &vk);
        env.storage().instance().set(&VERIFY_CNT, &0u32);
        env.storage().instance().set(&INITIALIZED, &true);
        log!(
            &env,
            "ZKML verifier initialized with model commitment and verification key"
        );
    }

    /// Verify a Groth16 proof of ML inference.
    ///
    /// `public_inputs` is the concatenation of the 32-byte model commitment,
    /// the 32-byte input commitment, and the output bytes.
    pub fn verify_inference(
        env: Env,
        proof_a: Bytes,
        proof_b: Bytes,
        proof_c: Bytes,
        public_inputs: Bytes,
    ) -> Result<(), VerificationError> {
        if !env.storage().instance().has(&INITIALIZED) {
            return Err(VerificationError::ContractNotInitialized);
        }

        // Validate public inputs
        let stored_model_hash = env
            .storage()
            .instance()
            .get::<_, Bytes>(&MODEL_HASH)
            .ok_or(VerifierError::NotInitialized)?;

        if public_inputs.len() < 64 {
            return Err(VerificationError::PublicInputsTooShort);
        }

        // Deserialize proof points
        let proof_a_g1 = Self::deserialize_g1(&env, &proof_a)?;
        let proof_b_g2 = Self::deserialize_g2(&env, &proof_b)?;
        let proof_c_g1 = Self::deserialize_g1(&env, &proof_c)?;

        // Get verification key
        let vk: VerificationKey = env
            .storage()
            .instance()
            .get(&VERIFICATION_KEY)
            .ok_or(VerificationError::ContractNotInitialized)?;

        // Extract public inputs
        let model_hash = public_inputs.slice(0..32);
        let input_hash = public_inputs.slice(32..64);
        let output = public_inputs.slice(64..public_inputs.len());

        // Verify model hash matches stored commitment
        let stored_model_hash: Bytes = env
            .storage()
            .instance()
            .get(&MODEL_HASH)
            .ok_or(VerificationError::ContractNotInitialized)?;
        if model_hash != stored_model_hash {
            return Err(VerificationError::VerificationFailed);
        }

        // Convert public inputs to field elements for L computation
        let bn254 = env.crypto().bn254();

        // L = sum(public_input_i * vk_ic_i)
        // Public inputs: model_hash (32 bytes), input_hash (32 bytes), output (variable)
        // We need to convert these to Bn254Fr scalars
        let mut l = vk
            .ic
            .get(0)
            .ok_or(VerificationError::MalformedVerificationKey)?;

        // Convert model_hash to scalar and multiply with ic[1]
        let model_scalar = Self::bytes_to_fr(&env, &model_hash);
        let ic1 = vk
            .ic
            .get(1)
            .ok_or(VerificationError::MalformedVerificationKey)?;
        let term1 = bn254.g1_mul(&ic1, &model_scalar);
        l = bn254.g1_add(&l, &term1);

        // Convert input_hash to scalar and multiply with ic[2]
        let input_scalar = Self::bytes_to_fr(&env, &input_hash);
        let ic2 = vk
            .ic
            .get(2)
            .ok_or(VerificationError::MalformedVerificationKey)?;
        let term2 = bn254.g1_mul(&ic2, &input_scalar);
        l = bn254.g1_add(&l, &term2);

        // Convert output to scalar and multiply with ic[3]
        let output_scalar = Self::bytes_to_fr(&env, &output);
        let ic3 = vk
            .ic
            .get(3)
            .ok_or(VerificationError::MalformedVerificationKey)?;
        let term3 = bn254.g1_mul(&ic3, &output_scalar);
        l = bn254.g1_add(&l, &term3);

        // Pairing check: e(A, B) == e(alpha, beta) * e(L, gamma) * e(C, delta)
        // Equivalent to: e(-A, B) * e(alpha, beta) * e(L, gamma) * e(C, delta) == 1
        let neg_a = -proof_a_g1;
        let vp1 = vec![&env, neg_a, vk.alpha, l, proof_c_g1];
        let vp2 = vec![&env, proof_b_g2, vk.beta, vk.gamma, vk.delta];

        if !bn254.pairing_check(vp1, vp2) {
            return Err(VerificationError::VerificationFailed);
        }

        // Verification succeeded - record result
        let record = InferenceRecord {
            model_hash,
            output,
            verified_at: env.ledger().sequence(),
        };
        env.storage().instance().set(&LAST_RESULT, &record);

        let count: u32 = env.storage().instance().get(&VERIFY_CNT).unwrap_or(0);
        env.storage().instance().set(&VERIFY_CNT, &(count + 1));

        #[allow(deprecated)]
        env.events()
            .publish((symbol_short!("verified"),), record.verified_at);

        Ok(())
    }

    /// Deserialize a G1 point from 64 bytes (Ethereum-compatible format).
    fn deserialize_g1(env: &Env, bytes: &Bytes) -> Result<Bn254G1Affine, VerificationError> {
        if bytes.len() != 64 {
            return Err(VerificationError::MalformedProofA);
        }
        let mut array = [0u8; 64];
        bytes.copy_into_slice(&mut array);
        Ok(Bn254G1Affine::from_array(env, &array))
    }

    /// Deserialize a G2 point from 128 bytes (Ethereum-compatible format).
    fn deserialize_g2(env: &Env, bytes: &Bytes) -> Result<Bn254G2Affine, VerificationError> {
        if bytes.len() != 128 {
            return Err(VerificationError::MalformedProofB);
        }
        let mut array = [0u8; 128];
        bytes.copy_into_slice(&mut array);
        Ok(Bn254G2Affine::from_array(env, &array))
    }

    /// Convert bytes to a Bn254Fr scalar field element.
    fn bytes_to_fr(env: &Env, bytes: &Bytes) -> Bn254Fr {
        let mut array = [0u8; 32];
        let len = bytes.len().min(32) as usize;
        bytes.copy_into_slice(&mut array);
        // Pad with zeros if less than 32 bytes
        for i in len..32 {
            array[i] = 0;
        }
        let bytes_ref = Bytes::from_slice(env, &array);
        U256::from_be_bytes(env, &bytes_ref).into()
    }

    /// Retrieve the last verified inference result.
    pub fn get_result(env: Env) -> InferenceRecord {
        env.storage()
            .instance()
            .get(&LAST_RESULT)
            .expect("no inference result has been recorded yet")
    }

    /// Retrieve the registered model commitment.
    pub fn get_model_hash(env: Env) -> Bytes {
        env.storage()
            .instance()
            .get(&MODEL_HASH)
            .expect("contract is not initialized")
    }

    /// Retrieve the number of verified proofs so far.
    pub fn get_verification_count(env: Env) -> u32 {
        env.storage().instance().get(&VERIFY_CNT).unwrap_or(0)
    }

    /// Return the contract interface version.
    pub fn version(_env: Env) -> u32 {
        VERSION
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use soroban_sdk::Env;

    fn create_dummy_vk(env: &Env) -> VerificationKey {
        // Use the G1 generator point (1, 2) which is valid
        let g1_bytes: [u8; 64] = [
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 2,
        ];
        let g2_bytes = [0u8; 128];
        let g1 = Bn254G1Affine::from_array(env, &g1_bytes);
        let g2 = Bn254G2Affine::from_array(env, &g2_bytes);

        VerificationKey {
            alpha: g1.clone(),
            beta: g2.clone(),
            gamma: g2.clone(),
            delta: g2.clone(),
            ic: vec![env, g1.clone(), g1.clone(), g1.clone(), g1],
        }
    }

    #[test]
    fn test_initialize() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);
        let model_hash = Bytes::from_slice(&env, &[1u8; 32]);
        let vk = create_dummy_vk(&env);
        client.initialize(&model_hash, &vk);
    }

    #[test]
    #[should_panic(expected = "contract is already initialized")]
    fn test_double_initialize() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);
        let model_hash = Bytes::from_slice(&env, &[1u8; 32]);
        let vk = create_dummy_vk(&env);
        client.initialize(&model_hash, &vk);
        client.initialize(&model_hash, &vk);
    }
}

#[cfg(test)]
mod test_guards {
    use super::*;
    use soroban_sdk::Env;

    fn create_dummy_vk(env: &Env) -> VerificationKey {
        // Use the G1 generator point (1, 2) which is valid
        let g1_bytes: [u8; 64] = [
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 2,
        ];
        let g2_bytes = [0u8; 128];
        let g1 = Bn254G1Affine::from_array(env, &g1_bytes);
        let g2 = Bn254G2Affine::from_array(env, &g2_bytes);

        VerificationKey {
            alpha: g1.clone(),
            beta: g2.clone(),
            gamma: g2.clone(),
            delta: g2.clone(),
            ic: vec![env, g1.clone(), g1.clone(), g1.clone(), g1],
        }
    }

    fn setup(env: &Env) -> ZkmlVerifierContractClient<'_> {
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(env, &contract_id);
        let model_hash = Bytes::from_slice(env, &[3u8; 32]);
        let vk = create_dummy_vk(env);
        client.initialize(&model_hash, &vk);
        client
    }

    #[test]
    fn verify_malformed_proof_a() {
        let env = Env::default();
        let client = setup(&env);

        let proof_a = Bytes::from_slice(&env, &[0u8; 8]); // Wrong length
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 64]);
        let public_inputs = Bytes::from_slice(&env, &[7u8; 96]);

        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        assert_eq!(result, Err(Ok(VerificationError::MalformedProofA)));
    }

    #[test]
    fn verify_malformed_proof_b() {
        let env = Env::default();
        let client = setup(&env);

        // Use valid G1 generator point for proof_a and proof_c
        let g1_bytes: [u8; 64] = [
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 2,
        ];
        let proof_a = Bytes::from_slice(&env, &g1_bytes);
        let proof_b = Bytes::from_slice(&env, &[0u8; 8]); // Wrong length
        let proof_c = Bytes::from_slice(&env, &g1_bytes);
        let public_inputs = Bytes::from_slice(&env, &[7u8; 96]);

        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        // Should fail due to malformed proof_b (wrong length)
        assert!(result.is_err());
    }

    #[test]
    fn verify_malformed_proof_c() {
        let env = Env::default();
        let client = setup(&env);

        // Use valid G1 generator point for proof_a
        let g1_bytes: [u8; 64] = [
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 2,
        ];
        let proof_a = Bytes::from_slice(&env, &g1_bytes);
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 8]); // Wrong length
        let public_inputs = Bytes::from_slice(&env, &[7u8; 96]);
        let res = client.try_verify_inference(&proof, &proof, &proof, &public_inputs);

        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        // Should fail due to malformed proof_c (wrong length)
        assert!(result.is_err());
    }

    #[test]
    fn verify_public_inputs_too_short() {
        let env = Env::default();
        let client = setup(&env);

        let proof_a = Bytes::from_slice(&env, &[0u8; 64]);
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 64]);
        let public_inputs = Bytes::from_slice(&env, &[7u8; 32]); // Too short

        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        assert_eq!(result, Err(Ok(VerificationError::PublicInputsTooShort)));
    }

    #[test]
    fn verify_wrong_model_hash() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);

        // Initialize with model hash [3u8; 32]
        let model_hash = Bytes::from_slice(&env, &[3u8; 32]);
        let vk = create_dummy_vk(&env);
        client.initialize(&model_hash, &vk);

        // Try to verify with different model hash [5u8; 32]
        let proof_a = Bytes::from_slice(&env, &[0u8; 64]);
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 64]);
        let public_inputs = Bytes::from_slice(&env, &[5u8; 96]); // Wrong model hash

        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        assert_eq!(result, Err(Ok(VerificationError::VerificationFailed)));
    }
}

#[cfg(test)]
mod test_poseidon_cross_check {
    use super::*;
    use soroban_sdk::Env;

    fn create_dummy_vk(env: &Env) -> VerificationKey {
        // Use the G1 generator point (1, 2) which is valid
        let g1_bytes: [u8; 64] = [
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 2,
        ];
        let g2_bytes = [0u8; 128];
        let g1 = Bn254G1Affine::from_array(env, &g1_bytes);
        let g2 = Bn254G2Affine::from_array(env, &g2_bytes);

        VerificationKey {
            alpha: g1.clone(),
            beta: g2.clone(),
            gamma: g2.clone(),
            delta: g2.clone(),
            ic: vec![env, g1.clone(), g1.clone(), g1.clone(), g1],
        }
    }

    #[test]
    fn verify_before_initialize_returns_error() {
        let env = Env::default();
        let contract_id = env.register(ZkmlVerifierContract, ());
        let client = ZkmlVerifierContractClient::new(&env, &contract_id);
        let proof_a = Bytes::from_slice(&env, &[0u8; 64]);
        let proof_b = Bytes::from_slice(&env, &[0u8; 128]);
        let proof_c = Bytes::from_slice(&env, &[0u8; 64]);
        let public_inputs = Bytes::from_slice(&env, &[7u8; 96]);

        let result = client.try_verify_inference(&proof_a, &proof_b, &proof_c, &public_inputs);
        assert_eq!(result, Err(Ok(VerificationError::ContractNotInitialized)));
    }

    #[test]
    fn model_commitment_is_reproducible() {
        let env = Env::default();
        let test_data = [1u8, 2u8, 3u8];
        let commitment = Bytes::from_slice(&env, &test_data);
        assert_eq!(commitment, Bytes::from_slice(&env, &test_data));
    }
}
